import type { Metadata } from "next";
import Link from "next/link";
import { Arrow } from "@/components/icons";
import { CtaBand, PageHero } from "@/components/ui";
import { processSteps } from "@/lib/data";
import { canonical } from "@/lib/seo";

export const metadata: Metadata = { title: "Proces współpracy", description: "Zobacz, jak krok po kroku wygląda współpraca nad stroną lub sklepem internetowym.", alternates: canonical("/proces") };

export default function ProcessPage() { return <><PageHero eyebrow="Proces współpracy" title="Dobra strona zaczyna się od" italic="dobrej rozmowy." text="Prosty, czytelny proces pozwala nam skupić energię na właściwych rzeczach. Bez zgadywania, przeciągających się decyzji i technicznego chaosu."/><section className="section-space"><div className="container-page"><div className="relative mx-auto max-w-5xl">{processSteps.map((step,i)=><article key={step.number} className="grid gap-5 border-t border-black/10 py-10 md:grid-cols-[110px_1fr_1fr] md:items-start md:py-14"><span className="font-serif text-5xl text-gold/50">{step.number}</span><h2 className="font-serif text-3xl md:text-4xl">{step.title}</h2><div><p className="text-sm leading-7 text-muted">{step.text}</p><p className="mt-4 text-[.62rem] font-bold uppercase tracking-widest text-gold">{["30-45 min rozmowy", "Oferta + harmonogram", "2 rundy uwag", "Publikacja + instrukcja"][i]}</p></div></article>)}</div></div></section><section className="bg-cream/70"><div className="container-page grid gap-10 py-20 lg:grid-cols-2"><div><p className="eyebrow">Po Twojej stronie</p><h2 className="mt-6 font-serif text-5xl">Czego będę<br/>potrzebować?</h2></div><div className="grid gap-3 sm:grid-cols-2">{["informacji o marce", "oferty lub listy usług", "logo i materiałów marki", "zdjęć lub planu ich wykonania", "regularnego feedbacku", "jednej osoby decyzyjnej"].map((x,i)=><div key={x} className="flex gap-3 border-b border-black/10 py-4 text-sm"><span className="text-gold">0{i+1}</span>{x}</div>)}</div></div></section><section className="section-space"><div className="container-page text-center"><p className="eyebrow mx-auto w-fit">Pierwszy krok</p><h2 className="section-heading mx-auto mt-6 max-w-3xl">Opowiedz mi, gdzie jest dziś<br/><em className="text-gold">Twoja marka.</em></h2><Link href="/kontakt" className="btn-primary mt-9">Napisz do mnie <Arrow/></Link></div></section><CtaBand/></>; }
