import type { Metadata } from "next";
import Link from "next/link";
import { LegalPage } from "@/components/legal-page";
import { canonical } from "@/lib/seo";

export const metadata: Metadata = { title: "Polityka prywatności", description: "Informacje o przetwarzaniu danych osobowych w serwisie Braided Digital.", alternates: canonical("/polityka-prywatnosci") };

export default function PrivacyPage() { return <LegalPage eyebrow="Dokumenty" title="Polityka prywatności" intro="Dowiedz się, jakie dane mogą być przetwarzane podczas korzystania ze strony i kontaktu z Braided Digital.">
  <h2>1. Administrator danych</h2><p>Administratorem danych osobowych jest Marek Białkowski, prowadzący działalność nierejestrowaną pod marką Braided Digital (dalej: „Administrator”), adres korespondencyjny: Chylin 35, 62-710 Władysławów. Kontakt z Administratorem jest możliwy przez e-mail <a href="mailto:ma.atelier.kontakt@gmail.com">ma.atelier.kontakt@gmail.com</a>, telefonicznie lub przez WhatsApp pod numerem <a href="https://wa.me/48730195530">+48 730 195 530</a>.</p>
  <h2>2. Jakie dane są przetwarzane</h2><p>W zależności od sposobu kontaktu mogą to być: imię i nazwisko, nazwa firmy lub marki, adres e-mail, numer telefonu, treść wiadomości, informacje dotyczące planowanego projektu oraz dane zawarte w późniejszej korespondencji i dokumentach rozliczeniowych.</p><p>Serwer obsługujący stronę może automatycznie zapisywać dane techniczne, takie jak adres IP, rodzaj przeglądarki, czas żądania i odwiedzony adres. Dane te służą bezpieczeństwu i prawidłowemu działaniu serwisu.</p>
  <h2>3. Formularze i WhatsApp</h2><p>Formularz kontaktowy przygotowuje wiadomość lokalnie w przeglądarce i przekazuje ją do WhatsApp po przejściu użytkownika do tej usługi. Kalkulator wyceny przesyła podane dane do serwera strony w celu obliczenia wyniku i obsługi zapytania. Korzystanie z WhatsApp podlega również zasadom prywatności dostawcy tej usługi, spółek z grupy Meta.</p>
  <h2>4. Cele i podstawy prawne</h2><ul><li>udzielenie odpowiedzi i przygotowanie oferty - działania przed zawarciem umowy oraz prawnie uzasadniony interes Administratora,</li><li>zawarcie i wykonanie umowy - niezbędność do wykonania umowy,</li><li>rozliczenia i dokumentacja podatkowa - obowiązek prawny,</li><li>ustalenie, dochodzenie lub obrona roszczeń - prawnie uzasadniony interes Administratora,</li><li>bezpieczeństwo i administracja serwisu - prawnie uzasadniony interes Administratora.</li></ul>
  <h2>5. Odbiorcy danych</h2><p>Dane mogą być powierzane podmiotom zapewniającym hosting i infrastrukturę strony, dostawcom poczty lub komunikatorów, narzędzi biurowych, obsługi księgowej i prawnej - wyłącznie w zakresie niezbędnym do realizacji danego celu. Strona jest przygotowana do hostowania w infrastrukturze Vercel. Wiadomości wysyłane przez WhatsApp są obsługiwane przez dostawcę tej usługi.</p>
  <h2>6. Przekazywanie poza EOG</h2><p>Niektórzy dostawcy technologiczni mogą przetwarzać dane poza Europejskim Obszarem Gospodarczym. W takich przypadkach transfer powinien opierać się na mechanizmach dopuszczonych przez RODO, w szczególności decyzji stwierdzającej odpowiedni stopień ochrony lub standardowych klauzulach umownych.</p>
  <h2>7. Czas przechowywania</h2><ul><li>zapytania bez zawarcia umowy - co do zasady do 12 miesięcy od zakończenia kontaktu,</li><li>dane związane z umową - przez okres jej realizacji i do upływu terminów przedawnienia roszczeń,</li><li>dokumentacja rozliczeniowa - przez okres wymagany przepisami podatkowymi,</li><li>logi techniczne - przez okres wynikający z ustawień dostawcy hostingu i potrzeb bezpieczeństwa.</li></ul>
  <h2>8. Twoje prawa</h2><p>Masz prawo żądać dostępu do danych, ich sprostowania, usunięcia lub ograniczenia przetwarzania, przeniesienia danych, a także wnieść sprzeciw, gdy podstawą jest prawnie uzasadniony interes. Jeżeli podstawą jest zgoda, możesz ją wycofać bez wpływu na zgodność wcześniejszego przetwarzania.</p><p>Masz także prawo złożyć skargę do Prezesa Urzędu Ochrony Danych Osobowych.</p>
  <h2>9. Dobrowolność i automatyczne decyzje</h2><p>Podanie danych jest dobrowolne, ale bez danych kontaktowych udzielenie odpowiedzi lub realizacja usługi może nie być możliwa. Dane nie są wykorzystywane do zautomatyzowanego podejmowania decyzji ani profilowania.</p>
  <h2>10. Cookies i zmiany dokumentu</h2><p>Informacje o pamięci przeglądarki i zewnętrznych treściach znajdują się w <Link href="/polityka-cookies">polityce cookies</Link>. Dokument może być aktualizowany, jeżeli zmienią się funkcje strony, dostawcy albo przepisy. Aktualna wersja jest zawsze publikowana pod tym adresem.</p>
</LegalPage>; }
