import type { Metadata } from "next";
import { LegalPage } from "@/components/legal-page";
import { canonical } from "@/lib/seo";

export const metadata: Metadata = { title: "Regulamin", description: "Regulamin świadczenia usług i korzystania z serwisu Braided Digital.", alternates: canonical("/regulamin") };

export default function TermsPage() { return <LegalPage eyebrow="Dokumenty" title="Regulamin usług" intro="Zasady korzystania ze strony oraz współpracy przy projektowaniu stron internetowych, sklepów i usługach technicznych.">
  <h2>1. Informacje ogólne</h2><p>Usługi pod marką Braided Digital świadczy Marek Białkowski w ramach działalności nierejestrowanej w rozumieniu art. 5 ustawy Prawo przedsiębiorców, dalej „Usługodawca”. Adres korespondencyjny: Chylin 35, 62-710 Władysławów. Kontakt: e-mail <a href="mailto:ma.atelier.kontakt@gmail.com">ma.atelier.kontakt@gmail.com</a>, telefon i WhatsApp <a href="https://wa.me/48730195530">+48 730 195 530</a>. Pełne dane stron są również wskazywane w indywidualnej ofercie przed zawarciem umowy.</p><p>Regulamin określa zasady korzystania z serwisu oraz zawierania i wykonywania umów dotyczących między innymi stron internetowych, sklepów, linków w bio, konsultacji i wsparcia WordPress lub WooCommerce.</p>
  <h2>2. Wymagania techniczne i usługi elektroniczne</h2><p>Do korzystania ze strony potrzebne są urządzenie z dostępem do internetu, aktualna przeglądarka i włączona obsługa JavaScript. Bezpłatną usługą elektroniczną jest udostępnienie treści serwisu oraz formularza, który przygotowuje wiadomość do wysłania przez WhatsApp. Użytkownik może zakończyć korzystanie z tych usług w każdej chwili przez zamknięcie strony.</p><p>Zabronione jest przekazywanie treści bezprawnych, złośliwego kodu, podejmowanie prób naruszenia bezpieczeństwa oraz używanie serwisu w sposób naruszający prawa innych osób.</p>
  <h2>3. Zapytanie, oferta i zawarcie umowy</h2><ol><li>Wysłanie zapytania nie oznacza zawarcia umowy i jest bezpłatne.</li><li>Po rozmowie Usługodawca przekazuje indywidualną ofertę określającą zakres, cenę, harmonogram, liczbę rund poprawek, warunki płatności oraz dane stron.</li><li>Umowa zostaje zawarta po zaakceptowaniu oferty w uzgodnionej formie i, jeżeli oferta tak stanowi, wpłacie zadatku lub pierwszej części wynagrodzenia.</li><li>W przypadku rozbieżności pierwszeństwo przed niniejszym regulaminem mają indywidualne ustalenia zapisane w ofercie lub umowie.</li></ol>
  <h2>4. Ceny i płatności</h2><p>Ceny na stronie mają charakter orientacyjny. Ostateczna cena zależy od zakresu, funkcji, liczby podstron, materiałów oraz terminu. Przed rozpoczęciem klient otrzymuje stałą cenę lub jasną metodę jej obliczenia. Projekty mogą być rozliczane etapami. Koszty domeny, hostingu, płatnych wtyczek, licencji, bramek płatniczych i usług podmiotów trzecich ponosi klient, jeżeli oferta nie stanowi inaczej.</p><p>Usługodawca prowadzący działalność nierejestrowaną wystawia rachunek lub fakturę na żądanie, zgodnie z obowiązującymi przepisami i swoim statusem podatkowym.</p>
  <h2>5. Obowiązki klienta</h2><p>Klient przekazuje prawdziwe informacje, materiały w uzgodnionych terminach oraz feedback przez wskazany kanał. Klient oświadcza, że posiada prawa do przekazanych nazw, logo, tekstów, zdjęć, fontów i innych materiałów oraz że ich wykorzystanie nie narusza praw osób trzecich.</p><p>Opóźnienie w przekazaniu materiałów lub akceptacji może przesunąć harmonogram. Zakres dodatkowy, wykraczający poza zaakceptowaną ofertę, wymaga osobnej wyceny.</p>
  <h2>6. Realizacja i odbiór</h2><p>Projekt jest realizowany etapami opisanymi w ofercie. Klient zgłasza uwagi w ramach ustalonej liczby rund. Brak uwag w uzgodnionym terminie może oznaczać akceptację danego etapu, jeżeli oferta wyraźnie tak stanowi. Przed publikacją wykonywane są uzgodnione testy na współczesnych przeglądarkach i typowych rozmiarach ekranów.</p><p>Po zapłacie pełnego wynagrodzenia i odbiorze Usługodawca przekazuje uzgodnione dostępy lub pliki. Zakres wsparcia po publikacji wynika z oferty. Problemy spowodowane późniejszymi zmianami klienta, aktualizacjami zewnętrznych usług lub awarią hostingu nie stanowią wady wykonania.</p>
  <h2>7. Prawa autorskie</h2><p>Do czasu pełnej płatności prawa do przygotowanych rezultatów pozostają przy Usługodawcy. Z chwilą zapłaty klient otrzymuje prawa lub licencję w zakresie dokładnie wskazanym w ofercie. Elementy osób trzecich, w tym fonty, zdjęcia stockowe, motywy i wtyczki, podlegają ich własnym licencjom.</p><p>Usługodawca może prezentować ukończony projekt w portfolio po jego publicznym uruchomieniu, chyba że strony pisemnie ustalą inaczej.</p>
  <h2>8. Konsument i odstąpienie od umowy</h2><p>Klient będący konsumentem lub przedsiębiorcą na prawach konsumenta, który zawiera umowę na odległość, co do zasady ma 14 dni na odstąpienie od umowy bez podawania przyczyny. Jeżeli klient wyraźnie zażąda rozpoczęcia usługi przed upływem tego terminu, w razie odstąpienia może być zobowiązany zapłacić za część wykonaną do chwili odstąpienia. Po pełnym wykonaniu usługi, rozpoczętym za uprzednią wyraźną zgodą i po poinformowaniu o utracie prawa odstąpienia, prawo to może wygasnąć.</p><p>Oświadczenie można złożyć jednoznaczną wiadomością na dane kontaktowe Usługodawcy. Szczegółowe pouczenie i wzór formularza odstąpienia są przekazywane konsumentowi przed zawarciem konkretnej umowy.</p>
  <h2>9. Reklamacje</h2><p>Reklamację należy przesłać przez dane kontaktowe podane w ofercie, opisując problem, datę jego zauważenia, oczekiwane rozwiązanie i dane pozwalające zidentyfikować projekt. Usługodawca odpowiada konsumentowi w terminie 14 dni. Regulamin nie ogranicza uprawnień wynikających z bezwzględnie obowiązujących przepisów.</p>
  <h2>10. Odpowiedzialność i usługi zewnętrzne</h2><p>Usługodawca odpowiada za zgodność wykonania z zaakceptowaną ofertą, ale nie gwarantuje określonej pozycji w wyszukiwarkach, poziomu sprzedaży ani nieprzerwanego działania usług podmiotów trzecich. Klient odpowiada za legalność swojej oferty, treści, regulaminu sklepu, polityk oraz przetwarzania danych w swojej działalności, o ile ich przygotowanie nie było osobnym przedmiotem umowy.</p>
  <h2>11. Postanowienia końcowe</h2><p>Do umów stosuje się prawo polskie. Konsument może korzystać z pozasądowych metod rozpatrywania sporów, w tym pomocy właściwego rzecznika konsumentów lub Inspekcji Handlowej. Regulamin może zostać zmieniony z ważnych przyczyn prawnych lub technicznych; zmiany nie naruszają praw nabytych ani warunków wcześniej zawartych umów.</p>
</LegalPage>; }
