import type { Metadata } from "next";
import Link from "next/link";
import { Arrow, CheckIcon } from "@/components/icons";
import { CtaBand, PageHero } from "@/components/ui";
import { pricing } from "@/lib/data";
import { PackagePreview } from "@/components/package-demos";

export const metadata: Metadata = { title: "Cennik orientacyjny", description: "Orientacyjne ceny stron internetowych, sklepów online i linków w bio. Poznaj przykładowe zakresy." };

export default function PricingPage() { return <><PageHero eyebrow="Cennik orientacyjny" title="Dobra strona na" italic="każdą kieszeń." text="Nie musisz być dużą firmą, żeby mieć profesjonalne miejsce w sieci. Pakiety ułożyłam tak, aby można było zacząć małym krokiem i rozwijać stronę razem z marką."/>
  <section className="border-b border-black/10 bg-cream/70"><div className="container-page grid gap-5 py-8 text-center sm:grid-cols-3"><div><strong className="block font-serif text-2xl">od 390 zł</strong><span className="text-[.6rem] uppercase tracking-widest text-muted">najmniejszy pakiet</span></div><div><strong className="block font-serif text-2xl">0 zł</strong><span className="text-[.6rem] uppercase tracking-widest text-muted">za pierwszą rozmowę</span></div><div><strong className="block font-serif text-2xl">2-3 części</strong><span className="text-[.6rem] uppercase tracking-widest text-muted">możliwy podział płatności</span></div></div></section>
  <section className="section-space"><div className="container-page"><div className="mb-12 max-w-2xl"><p className="eyebrow">Pakiety i prezentacje</p><h2 className="section-heading mt-6">Zobacz, co naprawdę<br/><em className="text-gold">może powstać.</em></h2><p className="mt-5 text-sm leading-7 text-muted">Każdy pakiet ma inną przykładową oprawę i osobne demo. To koncepcje pokazujące możliwy zakres - finalny projekt zawsze dopasowuję do Twojej marki.</p></div><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{pricing.map(plan=><article key={plan.title} className={`relative flex flex-col border p-5 md:p-7 ${plan.featured ? "border-gold bg-ink text-white shadow-2xl" : plan.handmade ? "border-gold bg-[#f1e8db]" : "border-black/10 bg-paper"}`}>{(plan.featured || plan.handmade) && <span className="absolute right-0 top-0 z-10 bg-gold px-4 py-2 text-[.52rem] font-bold uppercase tracking-widest text-white">{plan.handmade ? "Dla handmade" : "Popularny start"}</span>}<PackagePreview slug={plan.slug}/><p className={`text-[.58rem] font-bold uppercase tracking-[.18em] ${plan.featured ? "text-gold-light" : "text-gold"}`}>{plan.tag} · {plan.time}</p><h2 className="mt-5 font-serif text-3xl">{plan.title}</h2><p className="mt-2 font-serif text-3xl text-gold">{plan.price}</p><p className={`mt-5 min-h-20 text-xs leading-6 ${plan.featured ? "text-white/55" : "text-muted"}`}>{plan.lead}</p><ul className={`mt-6 space-y-3 border-t pt-5 ${plan.featured ? "border-white/10" : "border-black/10"}`}>{plan.features.map(x=><li key={x} className="flex items-center gap-2 text-xs"><CheckIcon className="size-4 text-gold"/>{x}</li>)}</ul><div className="mt-8 grid grid-cols-2 gap-2"><Link href={`/demo/${plan.slug}`} className={plan.featured ? "btn-light !min-h-11 !px-2" : "btn-secondary !min-h-11 !px-2"}>Zobacz demo</Link><Link href={`/kontakt?pakiet=${encodeURIComponent(plan.title)}`} className="btn-primary !min-h-11 !px-2">Zapytaj <Arrow/></Link></div></article>)}</div><p className="mt-8 text-center text-xs text-muted">Prezentacje są przykładowymi koncepcjami, nie gotowymi szablonami ani realizacjami klientów. Twój projekt otrzyma własny charakter.</p></div></section>
  <section className="bg-ink text-white"><div className="container-page py-20"><div className="grid gap-10 lg:grid-cols-[.7fr_1.3fr]"><div><p className="eyebrow">Małe zadania</p><h2 className="mt-6 font-serif text-5xl">Nie zawsze potrzeba<br/><em className="text-gold-light">wielkiego projektu.</em></h2><p className="mt-5 max-w-sm text-sm leading-7 text-white/50">Możesz zamówić pojedynczą poprawkę albo kilka godzin wsparcia. Najpierw potwierdzam, co da się zrobić w wybranym czasie.</p></div><div className="grid sm:grid-cols-2">{[{n:"01",t:"Konsultacja 60 min",p:"150 zł",d:"Rozmowa, audyt problemu i plan kolejnych działań."},{n:"02",t:"1 godzina pomocy",p:"od 120 zł",d:"Drobna poprawka WordPress lub WooCommerce."},{n:"03",t:"Pakiet 3 godzin",p:"od 320 zł",d:"Kilka zmian, aktualizacja treści lub ustawień sklepu."},{n:"04",t:"Dodatkowa podstrona",p:"od 250 zł",d:"Nowa podstrona dopasowana do działającej witryny."},{n:"05",t:"Dodanie produktów",p:"od 100 zł",d:"Wprowadzenie 5 gotowych produktów do sklepu."},{n:"06",t:"Podstawowy audyt",p:"od 190 zł",d:"Lista najważniejszych problemów i priorytetów zmian."}].map(x=><article key={x.n} className="border-b border-white/10 p-6 sm:border-l"><div className="flex items-center justify-between"><span className="text-[.55rem] text-gold-light">{x.n}</span><strong className="font-serif text-xl text-gold-light">{x.p}</strong></div><h3 className="mt-6 font-serif text-2xl">{x.t}</h3><p className="mt-3 text-xs leading-6 text-white/45">{x.d}</p></article>)}</div></div></div></section>
  <section className="bg-cream/70"><div className="container-page grid gap-12 py-20 lg:grid-cols-2"><div><p className="eyebrow">Płatność</p><h2 className="mt-6 font-serif text-5xl">Budżet ma pomagać,<br/>nie blokować.</h2><p className="mt-5 max-w-lg text-sm leading-7 text-muted">Przy projektach od 990 zł płatność możemy podzielić na 2 części, a przy sklepach na 3 etapy. Dzięki temu koszt rozkłada się razem z postępem prac.</p></div><div className="space-y-3">{["Bezpłatna rozmowa i wycena", "Stała cena ustalona przed startem", "Zadatek rezerwujący termin", "Możliwy rozwój etapami", "Brak obowiązkowego abonamentu"].map(x=><div key={x} className="flex items-center gap-3 border-b border-black/10 py-4 text-sm"><span className="grid size-8 place-items-center rounded-full bg-paper"><CheckIcon className="size-4 text-gold"/></span>{x}</div>)}</div></div></section><CtaBand/></>; }
