import type { Metadata } from "next";
import { ContactForm } from "@/components/contact-form";
import { WhatsAppIcon } from "@/components/icons";
import { PageHero } from "@/components/ui";
import { canonical } from "@/lib/seo";

export const metadata: Metadata = { title: "Kontakt i bezpłatna wycena", description: "Napisz o swojej marce, stronie lub sklepie — odpowiadam osobiście. Bezpłatna rozmowa i wycena bez zobowiązań. WhatsApp: +48 730 195 530.", alternates: canonical("/kontakt") };

export default function ContactPage() { return <><PageHero eyebrow="Kontakt" title="Opowiedz mi o" italic="swoim pomyśle." text="Nie potrzebujesz gotowego briefu. Napisz kilka zdań o marce, wyzwaniu i tym, co chcesz osiągnąć. Wrócę z pytaniami i propozycją następnego kroku."/><section className="section-space"><div className="container-page grid gap-14 lg:grid-cols-[.65fr_1.35fr]"><aside><p className="eyebrow">Bezpośrednio</p><h2 className="mt-6 font-serif text-4xl leading-tight">Zacznijmy od<br/>krótkiej wiadomości.</h2><p className="mt-5 max-w-sm text-sm leading-7 text-muted">Odpowiadam osobiście. W pierwszej wiadomości możesz podać link do obecnej strony lub profilu marki.</p><a href="https://wa.me/48730195530" target="_blank" rel="noreferrer" className="mt-8 flex max-w-sm items-center gap-4 border-y border-black/10 py-5"><span className="grid size-11 place-items-center rounded-full bg-gold text-white"><WhatsAppIcon className="size-5"/></span><span><span className="block text-[.55rem] font-bold uppercase tracking-widest text-gold">WhatsApp</span><span className="mt-1 block font-serif text-xl">+48 730 195 530</span></span></a><div className="mt-7 border-b border-black/10 pb-6"><span className="text-[.55rem] font-bold uppercase tracking-widest text-gold">E-mail</span><a href="mailto:ma.atelier.kontakt@gmail.com" className="mt-1 block break-all font-serif text-xl">ma.atelier.kontakt@gmail.com</a></div><div className="mt-7 text-xs leading-6 text-muted"><p>Działam zdalnie · współpraca w całej Polsce</p><p>Adres korespondencyjny: Chylin 35, 62-710 Władysławów</p><p className="mt-3 text-ink">Zwykle odpowiadam w ciągu 1-2 dni roboczych.</p></div></aside><div className="border border-black/10 bg-white/40 p-6 md:p-10"><p className="mb-8 text-[.62rem] font-bold uppercase tracking-[.2em] text-gold">Formularz zapytania</p><ContactForm/></div></div></section></>; }
