import type { Metadata } from "next";
import Link from "next/link";
import { Arrow, CheckIcon } from "@/components/icons";
import { CtaBand, PageHero, PortfolioMockup } from "@/components/ui";

export const metadata: Metadata = { title: "Portfolio", description: "Case study sklepu internetowego MA Atelier - aktualny podgląd strony, zakres prac i rozwiązania sprzedażowe." };

const scope = ["koncepcja i kierunek wizualny", "architektura informacji", "strona główna i sklep", "karty oraz kategorie produktów", "koszyk i proces zamówienia", "płatności i sposoby dostawy", "projekty indywidualne", "blog i podstawy SEO", "wersja mobilna", "analityka i dalszy rozwój"];

export default function PortfolioPage() { return <>
  <PageHero eyebrow="Portfolio" title="Projektuję to, co sama" italic="umiem prowadzić." text="MA Atelier to nie koncepcyjna makieta. To moja własna marka i działający sklep, które stworzyłam, rozwijam i poznaję od strony codziennych potrzeb małego biznesu handmade."/>
  <section className="section-space"><div className="container-page"><div className="mb-10 flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="eyebrow">Case study 01</p><h2 className="section-heading mt-6">MA Atelier</h2><p className="mt-4 max-w-2xl text-sm leading-7 text-muted">Poniżej widzisz aktualną stronę dokładnie tak, jak działa dzisiaj. Podgląd jest pobierany bezpośrednio z ma-atelier.pl, nie jest statyczną wizualizacją.</p></div><a href="https://ma-atelier.pl" target="_blank" rel="noreferrer" className="btn-primary shrink-0">Otwórz pełną stronę <Arrow/></a></div><PortfolioMockup/></div></section>
  <section className="bg-cream/70"><div className="container-page grid gap-14 py-20 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow">Od pomysłu do sklepu</p><h2 className="mt-6 font-serif text-5xl leading-none">Biżuteria z duszą.<br/><em className="text-gold">Sprzedaż z planem.</em></h2><p className="mt-6 max-w-lg text-sm leading-7 text-muted">Celem było stworzenie spokojnego, editorialowego miejsca dla ręcznie wykonywanej biżuterii z kamieni naturalnych. Strona pokazuje charakter produktów, ale prowadzi też czytelnie do sklepu i zamówień indywidualnych.</p><div className="mt-8 grid grid-cols-2 gap-4 border-y border-black/10 py-6 text-xs"><div><span className="block text-gold">Branża</span><span className="mt-1 block">Biżuteria handmade</span></div><div><span className="block text-gold">Platforma</span><span className="mt-1 block">WordPress + WooCommerce</span></div><div><span className="block text-gold">Charakter</span><span className="mt-1 block">Editorial / premium</span></div><div><span className="block text-gold">Status</span><span className="mt-1 block">Aktywny sklep</span></div></div></div><div className="grid gap-3 sm:grid-cols-2">{scope.map(item => <div key={item} className="flex items-center gap-3 border-b border-black/10 py-4 text-xs"><span className="grid size-7 shrink-0 place-items-center rounded-full bg-paper"><CheckIcon className="size-4 text-gold"/></span>{item}</div>)}</div></div></section>
  <section className="bg-ink text-white"><div className="container-page py-20"><div className="mb-12 max-w-2xl"><p className="eyebrow">Najważniejsze rozwiązania</p><h2 className="mt-6 font-serif text-5xl">Sklep dopasowany do<br/><em className="text-gold-light">małej marki handmade.</em></h2></div><div className="grid gap-px bg-white/10 md:grid-cols-2 lg:grid-cols-4">{[{n:"01",t:"Produkty na pierwszym planie",d:"Duże zdjęcia, spokojna typografia i czytelne ceny nie konkurują z biżuterią."},{n:"02",t:"Projekt indywidualny",d:"Osobna ścieżka dla klienta, który chce zamówić biżuterię tworzoną specjalnie dla niego."},{n:"03",t:"Proste zakupy",d:"Kategorie, koszyk, płatności i dostawy tworzą zrozumiałą drogę od inspiracji do zamówienia."},{n:"04",t:"Gotowość do rozwoju",d:"Nowe kolekcje, produkty i treści można dodawać bez przebudowy całej witryny."}].map(x=><article key={x.n} className="bg-ink p-7 md:p-9"><span className="text-[.58rem] text-gold-light">{x.n}</span><h3 className="mt-8 font-serif text-3xl">{x.t}</h3><p className="mt-4 text-xs leading-6 text-white/50">{x.d}</p></article>)}</div></div></section>
  <section className="section-space"><div className="container-page grid gap-12 lg:grid-cols-2 lg:items-center"><div><p className="eyebrow">Wiedza z praktyki</p><h2 className="section-heading mt-6">Nie kończę na<br/><em className="text-gold">„strona gotowa”.</em></h2></div><div><p className="text-sm leading-7 text-muted">Prowadzenie MA Atelier daje mi perspektywę, której nie daje sama praca projektowa. Znam dodawanie produktów, obsługę zamówień, kupony, dostawy, komunikację z klientem i drobne problemy, które pojawiają się dopiero po uruchomieniu sklepu.</p><p className="mt-4 text-sm leading-7 text-muted">Dlatego projektując dla małej marki, myślę także o osobie po drugiej stronie panelu: czy wszystko da się łatwo zmienić, czy obsługa nie zabiera zbyt wiele czasu i czy sklep może rosnąć bez kosztownej rewolucji.</p></div></div></section>
  <section className="section-space bg-cream/70"><div className="container-page text-center"><p className="mx-auto eyebrow w-fit">Następny projekt</p><h2 className="section-heading mx-auto mt-6 max-w-3xl">Może opowiemy tutaj<br/><em className="text-gold">historię Twojej marki?</em></h2><Link href="/kontakt" className="btn-primary mt-9">Porozmawiajmy <Arrow/></Link></div></section><CtaBand/>
</>; }
